Algoritmo "semnome"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : recebe um valor para raio e calcula area do circulo
// Autor(a)    : Alexandre Lemes
// Data atual  : 28/08/2023
Var
// Seção de Declarações das variáveis 
area: real
raio: real

Inicio
Escreva("Digite o valor do raio para calcular a area do circulo: ")
Leia(raio)
area <- 3.14159*raio^2
Escreva("O valor da area do circulo de raio   ", raio ," é", area)


Fimalgoritmo